# %% [markdown]
# # Companion Script: 4.4 Construction Rules
# 
# This notebook implements the computational solutions for the **Solved Problems** found in Section 4.4 of the MA2008B Lecture Notes: General Rules for Constructing Root Loci.
# 
# We build upon the previous tools by rigorously validating departure angles and more complex roots.

# %%
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import control as ctrl
from sympy import symbols, Eq, solve, diff

s, K = symbols('s K')

def print_section(title):
    print(f"\n{'='*50}")
    print(f"{title}")
    print(f"{'='*50}")

def style_plot(title):
    plt.title(title)
    plt.xlabel('Real Axis')
    plt.ylabel('Imaginary Axis')
    plt.grid(True)
    plt.axvline(x=0, color='k', linestyle='--', alpha=0.5)
    plt.axhline(y=0, color='k', linestyle='--', alpha=0.5)

# %% [markdown]
# ---
# ## Solved Problem 1: Apply All Rules
# 
# **Problem Statement:**
# Construct the root locus for
# $$ 1 + \frac{K}{(s+1)(s^2+2s+2)} = 0 $$
# using systematic rules.

# %%
print_section("Solved Problem 1: Apply All Rules")

# Define Plant F(s)
# Note: s^2 + 2s + 2 has roots at -1 +/- j
s_ctrl = ctrl.TransferFunction.s
F1 = 1 / ((s_ctrl + 1) * (s_ctrl**2 + 2*s_ctrl + 2))

poles = ctrl.poles(F1)
zeros = ctrl.zeros(F1)
n = len(poles)
m = len(zeros)

print(f"Open-loop Poles: {np.round(poles, 2)}")
print(f"Branches to infinity (n - m): {n - m}")

# Asymptotes
sigma_a = np.sum(poles) / n
angles_deg = [(2*k + 1)*180 / n for k in range(n)]

print(f"\nCentroid (sigma_a): {float(np.real(sigma_a)):.2f}")
print(f"Asymptote Angles: {angles_deg} degrees")

print("\nReal-Axis Segments (Odd Rule):")
print("  Between [-1, -infinity] -> 1 real pole to the right. (Locus exists)")

# Departure Angle Calculation for the complex pole p = -1 + j
p_test = -1 + 1j
# The angle from the other complex pole p_conj = -1 - j to p_test:
angle_from_conj = np.degrees(np.angle(p_test - (-1 - 1j)))
# The angle from the real pole p_real = -1 to p_test:
angle_from_real = np.degrees(np.angle(p_test - (-1)))

# Rule: theta_dep = 180 + sum(angle from zeros) - sum(angle from other poles)
theta_dep = 180 - (angle_from_conj + angle_from_real)
print(f"\nDeparture Angle from pole s_p = -1 + j:")
print(f"  Angle from (-1 - j): {angle_from_conj} deg")
print(f"  Angle from (-1): {angle_from_real} deg")
print(f"  Calculated Theta_dep: {theta_dep} degrees")

# Verify visually
plt.figure(figsize=(8, 8))
ctrl.root_locus(F1, plot=True, grid=False)
plt.plot(sigma_a, 0, 'rx', markersize=10, label=f'Centroid: {float(np.real(sigma_a)):.2f}')
style_plot("Root Locus: 1 + K/((s+1)(s^2+2s+2))")
plt.legend()
plt.xlim([-4, 2])
plt.ylim([-3, 3])
plt.show()

# %% [markdown]
# ---
# ## Solved Problem 2: Design Using Root Locus
# 
# **Problem Statement:**
# For the characteristic equation:
# $$ \Delta(s,K) = s(s+2) + K = 0 $$
# find the gain $K$ required to place the closed-loop poles exactly at $s = -1 \pm j$.

# %%
print_section("Solved Problem 2: Design Using Root Locus")

# Characteristic polynomial
Delta2 = s*(s + 2) + K

# Substitute the target root s = -1 + j into the characteristic equation
target_root = -1 + 1j
Delta2_subbed = (target_root)*(target_root + 2) + K

print(f"Substituting s = -1 + j into the characteristic equation:")
print(f"((-1 + j)(-1 + j + 2)) + K = 0")

# Expand the complex multiplication
val = (-1 + 1j) * (1 + 1j)
print(f"Calculated complex value: {val} + K = 0")

K_req = -np.real(val)
print(f"\nRequired Gain K: {K_req}")

# Validate
Delta_val = s**2 + 2*s + K_req
roots = solve(Eq(Delta_val, 0), s)
print(f"Roots generated by K = {K_req}: {roots}")

# %% [markdown]
# ---
# ## Solved Problem 3: Imaginary-Axis Crossing by Routh
# 
# **Problem Statement:**
# Determine the marginal stability crossing gain and frequency for:
# $$ \Delta(s,K) = s^3 + 3s^2 + 2s + K = 0 $$

# %%
print_section("Solved Problem 3: Imaginary-Axis Crossing by Routh")

print("Applying Routh-Hurwitz Array to s^3 + 3s^2 + 2s + K:")
print("s^3: 1        2")
print("s^2: 3        K")
print("s^1: (6-K)/3")
print("s^0: K")

# A crossing occurs when the first entry of the s^1 row is zero
K_crit = 6.0
print(f"\nEquation from s^1 row zeroes out at: K = {K_crit}")

# The crossover frequencies come from the auxiliary equation formed by the s^2 row
# 3s^2 + K = 0
aux_eq = Eq(3*s**2 + K_crit, 0)
crossing_points = solve(aux_eq, s)

print("Imaginary Axis Crossing Frequencies (s = ±jw):")
cp0 = complex(crossing_points[0].evalf())
cp1 = complex(crossing_points[1].evalf())
print(f"s = {cp0.real:.3f} + {cp0.imag:.3f}j")
print(f"s = {cp1.real:.3f} + {cp1.imag:.3f}j")

# Verify graphically
F3 = 1 / (s_ctrl**3 + 3*s_ctrl**2 + 2*s_ctrl)
plt.figure(figsize=(8, 8))
ctrl.root_locus(F3, plot=True, grid=False)
plt.plot([0, 0], [np.sqrt(2), -np.sqrt(2)], 'ro', markersize=8, label='Marginal Stability Crossings')
style_plot("Root locus showing Imaginary-Axis crossings")
plt.legend()
plt.xlim([-4, 2])
plt.ylim([-3, 3])
plt.show()
