# %% [markdown]
# # Companion Script: 4.6 Root Contour Diagrams
# 
# This notebook implements the computational solutions for the **Solved Problems** found in Section 4.6 of the MA2008B Lecture Notes: Root Contour Diagrams.
# 
# We look into parameter space design, local sensitivity analysis using derivatives, and identifying regions of admissible performance based on complex plane geometry.

# %%
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from sympy import symbols, Eq, solve, diff, I

s, K, K1, K2 = symbols('s K K1 K2')

# Helper function to print results nicely
def print_section(title):
    print(f"\n{'='*50}")
    print(f"{title}")
    print(f"{'='*50}")

# Helper to standardize plots
def style_plot(title):
    plt.title(title)
    plt.xlabel('Real Axis')
    plt.ylabel('Imaginary Axis')
    plt.grid(True)
    plt.axvline(x=0, color='k', linestyle='--', alpha=0.5)
    plt.axhline(y=0, color='k', linestyle='--', alpha=0.5)

# %% [markdown]
# ---
# ## Solved Problem 1: Parameter Space Design
# 
# **Problem Statement:**
# For the characteristic equation:
# $$ \Delta(s,K_1,K_2)=s(s+1)(s+3) + K_1(s+K_2) = 0 $$
# Find $(K_1, K_2)$ necessary to set the dominant poles at $\zeta = 0.7$, $\omega_n = 2$.

# %%
print_section("Solved Problem 1: Parameter Space Design")

zeta = 0.7
omega_n = 2.0

# Calculate desired dominant pole s_d
s_d_val = -zeta * omega_n + 1j * omega_n * np.sqrt(1 - zeta**2)
print(f"Target specified Damping Ratio: {zeta}")
print(f"Target specified Natural Frequency: {omega_n}")
print(f"Target Dominant Pole (s_d): {s_d_val:.3f}")

# Characteristic Equation representation evaluated at s_d
# Delta(s_d) = s_d*(s_d+1)*(s_d+3) + K1*s_d + K1*K2 = 0
A = s_d_val * (s_d_val + 1) * (s_d_val + 3)
print(f"\nValue of A = s_d(s_d+1)(s_d+3): {A:.3f}")

# The equation becomes A + K1*s_d + K1*K2 = 0
# Break it into real and imaginary parts:
# Re(A) + K1*Re(s_d) + K1*K2 = 0
# Im(A) + K1*Im(s_d) = 0

# From imaginary part:
# K1 * Im(s_d) = -Im(A)
K1_req = -np.imag(A) / np.imag(s_d_val)

# From real part:
# K1 * K2 = -Re(A) - K1 * Re(s_d)
K2_req = (-np.real(A) - K1_req * np.real(s_d_val)) / K1_req

print(f"\nSolving the simultaneous real/imaginary equations yields:")
print(f"Required parameter K1: {K1_req:.3f}")
print(f"Required parameter K2: {K2_req:.3f}")

# Validation
Delta_verify = s**3 + 4*s**2 + 3*s + K1_req*s + K1_req*K2_req
roots_generated = solve(Eq(Delta_verify, 0), s)

print(f"\nVerification - Roots generated by (K1, K2):")
for r in roots_generated:
    eval_r = complex(r.evalf())
    print(f"s = {eval_r:.3f}")

# %% [markdown]
# ---
# ## Solved Problem 2: Sensitivity Analysis
# 
# **Problem Statement:**
# Analyze the local sensitivity of the closed-loop pole locations to a 10% variation in $K$ for:
# $$ \Delta(s,K)=s^2+2s+K=0 $$
# Given nominal gain $K_0=4$, which places nominal poles at $s_0 = -1 \pm j\sqrt{3}$.

# %%
print_section("Solved Problem 2: Parameter Sensitivity Analysis")

Delta = s**2 + 2*s + K
K0 = 4.0

# Nominal pole calculation
nominal_roots = solve(Eq(Delta.subs(K, K0), 0), s)
s0 = nominal_roots[0] # Select the upper pole: -1 + i*sqrt(3)
print(f"Nominal Characteristic Equation: {Delta}")
print(f"Nominal Pole s_0 at K=4: {s0.evalf():.3f}")

# Calculate local sensitivity (ds/dK) using implicit differentiation:
# ds_dK = - (dDelta/dK) / (dDelta/ds)
dDelta_dK = diff(Delta, K)  # = 1
dDelta_ds = diff(Delta, s)  # = 2s + 2

ds_dK = -dDelta_dK / dDelta_ds
print(f"\nLocal Sensitivity Equation ds/dK: {ds_dK}")

# Evaluate at nominal pole s0
sensitivity_at_s0 = ds_dK.subs(s, s0)
print(f"Sensitivity evaluated at s_0: {sensitivity_at_s0.evalf():.3f}")

# Compare linear estimation vs. true displacement for a 10% change in K
delta_K = K0 * 0.10  # 10% increase = +0.4
linear_delta_s = sensitivity_at_s0 * delta_K

print(f"\n10% increase in K (Delta K = {delta_K})")
print(f"Linear Prediction of pole shift (Delta s): {linear_delta_s.evalf():.3f}")

# Calculate precise new pole
new_roots = solve(Eq(Delta.subs(K, K0 + delta_K), 0), s)
exact_new_pole = new_roots[0]
exact_delta_s = exact_new_pole - s0

print(f"Exact newly computed pole at K=4.4: {exact_new_pole.evalf():.3f}")
print(f"Exact actual pole shift (Delta s): {exact_delta_s.evalf():.3f}")
print("Conclusion: The linear sensitivity prediction closely tightly matches the exact shift!")

# %% [markdown]
# ---
# ## Solved Problem 3: Performance Region Interpretation
# 
# **Problem Statement:**
# Given the design requirements:
# $$ \zeta \ge 0.5 \quad \text{and} \quad \omega_n \le 4 $$
# Describe and visually plot the admissible dominant-pole region in the s-plane.

# %%
print_section("Solved Problem 3: Performance Region Interpretation")

print("Requirement 1: Damping ratio zeta >= 0.5")
print("  This defines a sector in the left-half-plane bounded by angle theta = arccos(0.5) = 60 degrees")
print("  measured from the negative real axis (or +/- 120 deg from the positive real axis).")

print("\nRequirement 2: Natural Frequency omega_n <= 4")
print("  This explicitly defines a circular disk centered at the origin with radius = 4.")

print("\nThe intersecting region of these two constraints forms a 'cone' slice of the disk in the LHP.")

# Visualizing the Admissible Region
plt.figure(figsize=(8, 8))

# Draw the natural frequency limit circle (radius 4)
theta_circle = np.linspace(0, 2*np.pi, 200)
x_circle = 4 * np.cos(theta_circle)
y_circle = 4 * np.sin(theta_circle)
plt.plot(x_circle, y_circle, 'b--', label='omega_n = 4 boundary')

# Draw the damping ratio limit rays
# angle from negative real axis is 60 deg -> angle from pos real axis is 120 and 240 deg
r = np.array([0, 5])
theta_damp1 = np.radians(120)
theta_damp2 = np.radians(240)

plt.plot(r * np.cos(theta_damp1), r * np.sin(theta_damp1), 'g-', label='zeta = 0.5 boundary')
plt.plot(r * np.cos(theta_damp2), r * np.sin(theta_damp2), 'g-')

# Fill the valid admissible region polygon
# The region is defined by the sector between 120 and 240 degrees up to radius 4
theta_region = np.linspace(theta_damp1, theta_damp2, 100)
x_fill = np.concatenate(([0], 4 * np.cos(theta_region), [0]))
y_fill = np.concatenate(([0], 4 * np.sin(theta_region), [0]))
plt.fill(x_fill, y_fill, 'g', alpha=0.3, label='Admissible Region')

style_plot("Admissible Performance Region (zeta >= 0.5, omega_n <= 4)")
plt.legend()
plt.xlim([-5, 1])
plt.ylim([-5, 5])
plt.gca().set_aspect('equal', adjustable='box')
plt.show()
