#import "../../utils.typ": *
== Root Locus of Control Systems

=== Mathematical Review

Consider a unity-feedback system with open-loop transfer function
$ L(s)=K C(s)P(s), $
so the closed-loop characteristic equation is
$ Delta(s,K)=1+L(s)=0. $
Root-locus design consists of choosing $K$ (and, when needed, a compensator $C$) so that selected roots of $Delta$ satisfy prescribed transient-performance requirements.

#definition[Second-Order Target Pair][
  For damping ratio $zeta in (0,1)$ and natural frequency $omega_n>0$, the target dominant pair is
  $ s_d=-zeta omega_n plus.minus j omega_n sqrt(1-zeta^2). $
  Approximate time-domain specifications are linked by
  $ t_s approx 4/(zeta omega_n) $
  (2% criterion) and
  $ M_p approx exp(-(zeta pi)/sqrt(1-zeta^2)). $
]

#proposition[Dominant-Pole Approximation][
  If non-dominant closed-loop poles lie sufficiently farther to the left than $s_d$, then transient response is well approximated by the second-order model generated by the dominant pair.
]

#proof[
  In the time domain, each pole contributes a modal term $e^(s_i t)$ multiplied by a polynomial factor.
  Modes with more negative real parts decay faster.
  Therefore, when non-dominant poles satisfy $Re(s_i) << Re(s_d)$, their contribution is negligible during the main transient interval, and the dominant pair determines overshoot and settling behavior to first order.
]

#theorem[Compensator Geometry on the Root Locus][
  A real compensator zero introduces positive phase near candidate points and attracts nearby branches, while a real compensator pole introduces negative phase and repels nearby branches.
  Consequently, lead compensation (zero closer to the origin than its pole) is used to increase phase margin and damping, whereas lag compensation (pole closer to the origin than its zero) is used primarily to improve low-frequency accuracy with smaller changes in transient geometry.
]

=== Solved Problems

#solved_problem[Settling-Time Feasibility Check][
  For $G(s)=K/(s(s+4))$ with unity feedback, determine whether the requirement $t_s=1"s"$ (2% criterion) can be met by gain adjustment alone.
]
#solution[
  The characteristic equation is
  $ s^2+4s+K=0. $
  Comparing with
  $ s^2+2 zeta omega_n s+omega_n^2=0, $
  we obtain
  $ 2 zeta omega_n=4, $
  hence
  $ zeta omega_n=2. $

  Under the 2% approximation,
  $ t_s approx 4/(zeta omega_n)=4/2=2"s". $
  Therefore $t_s=1"s"$ is not achievable by varying $K$ only in this structure.

  The best one can do without compensation is to keep real part $Re(s)=-2$ (for underdamped roots, $K>4$), which still gives approximately $2"s"$ settling time.
]

#solved_problem[Compensator Design][
  Design a lead compensator for $P(s)=1/(s(s+1))$ so that dominant poles are at
  $ s_d=-1 plus.minus j sqrt(3) $
  (equivalently $zeta=0.5$, $omega_n=2$).
]
#solution[
  Let
  $ C(s)=(s+z)/(s+p), quad p>z>0, $
  and evaluate the angle condition at
  $ s_d=-1+j sqrt(3). $

  For the plant poles at $0$ and $-1$, angle contributions are
  $ angle(s_d-0)=120 degree $
  and
  $ angle(s_d+1)=90 degree, $
  so the open-loop plant contributes $-210 degree$.
  To satisfy the root-locus condition (odd multiple of $180 degree$), the compensator must provide
  $ +30 degree $
  phase.

  Choose $z=2$, so
  $ angle(s_d+2)=60 degree. $
  Then require
  $ angle(s_d+p)=30 degree, $
  which gives
  $ p=4. $
  Thus
  $ C(s)=(s+2)/(s+4). $

  Now enforce the magnitude condition with
  $ L(s)=K C(s)P(s). $
  At $s_d$,
  $ |s_d+2|=2, quad |s_d|=2, quad |s_d+1|=sqrt(3), quad |s_d+4|=2 sqrt(3). $
  Hence
  $ |L(s_d)| = K (2)/(2 (sqrt(3)) (2 sqrt(3))) = K/6. $
  Setting $|L(s_d)|=1$ yields
  $ K=6. $

  One valid compensated design is therefore
  $ C(s)=(s+2)/(s+4), quad K=6. $
]

#solved_problem[Dominant-Pole Interpretation][
  For
  $ L(s)=K/((s+1)(s+2)(s+20)), $
  explain why the pair near $-1$ and $-2$ is treated as dominant in preliminary design.
]
#solution[
  The pole at $-20$ decays with time constant about $0.05"s"$, which is much faster than modes around $-1$ and $-2$.
  During most of the transient interval relevant to overshoot and settling, the fast mode is already negligible.
  Therefore the pair closest to the imaginary axis governs the visible response and is used for dominant-pole design approximations.
]

=== Supplementary Problems

#supplementary[Settling-Time Feasibility][
  For
  $ G(s)=K/(s(s+6)), $
  determine whether $t_s=1"s"$ (2% criterion) is achievable by gain adjustment alone.
]

#supplementary[Target Pole Gain][
  For
  $ G(s)=K/(s(s+3)), $
  compute $K$ that places poles at $-1.5 plus.minus 1.5j$.
]

#supplementary[Angle Deficiency][
  For
  $ P(s)=1/(s(s+1)(s+5)) $
  and target point
  $ s_d=-2 + j 2, $
  compute the compensator phase needed to satisfy the angle condition.
]

#supplementary[Lead Pole from Chosen Zero][
  For the previous setup, choose compensator zero at $-1$ and determine a real pole location that supplies the required phase.
]

#supplementary[Magnitude Condition with Lead][
  Using your compensator from the previous problem, compute the gain $K$ from the magnitude condition at $s_d$.
]

#supplementary[Lag-Compensator Interpretation][
  Explain, using pole-zero geometry, why a lag compensator typically changes steady-state accuracy more than transient pole location.
]

#supplementary[Dominant-Pole Validity Check][
  For poles at $-1.2 plus.minus 1.8j$ and an additional pole at $-9$, discuss whether second-order dominance is a reasonable approximation.
]

#supplementary[Overshoot to Damping Ratio][
  Compute $zeta$ corresponding to $M_p=10\%$, then write the target pole pair for $omega_n=4$.
]

#supplementary[Two-Spec Mapping][
  Given $M_p=5\%$ and $t_s=2"s"$ (2% criterion), determine $zeta$, $omega_n$, and the corresponding target pole location.
]

#supplementary[Compensator Comparison][
  Compare qualitatively the loci for
  $ C_1(s)=1, quad C_2(s)=(s+2)/(s+8), quad C_3(s)=(s+8)/(s+2), $
  with the same plant
  $ P(s)=1/(s(s+3)). $
  Identify which compensator acts as lead and which as lag, and describe expected transient impact.
]
